# Docker Compose
version: '3.3'
# Define services
services:
  apprestspring:
    image: moatez98/springbootauth:latest
    ports:
      - 8090:8081
    container_name: spring_boot_secuirty
    depends_on:
      - database
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/springbootsecurity?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: moatez
      SPRING_DATASOURCE_PASSWORD: moatez123
    networks:
      - spring_net
# Database Service (Mysql)
  database:
    image: mysql:latest
    container_name: mysql_container
    volumes:
      - ./Stockage/dbFiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: springbootsecurity
      MYSQL_USER: moatez
      MYSQL_PASSWORD: moatez123
      MYSQL_ROOT_PASSWORD: root
    networks:
      - spring_net
# Dec

networks:
  spring_net: